import hashlib
import os
from copy import deepcopy
from datetime import datetime, timezone

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap

from sca.config import VERSION
from sca.internal.loosening import Tailoring
from sca.internal.sca import SCA

ENCODING = 'UTF-8'


def escape_markdown_cell(value: object) -> str:
    return (str(value).replace('\\', '\\\\').replace('|', '\\|')
            .replace('\r\n', '<br>').replace('\n', '<br>').replace('\r', '<br>'))


class Guide:
    def __init__(self, baseline_path: str) -> None:
        self.baseline_path = baseline_path
        self.__yaml__ = YAML()
        with open(baseline_path, mode='r', encoding=ENCODING) as stream:
            self.__sca_yml__ = CommentedMap(self.__yaml__.load(stream))
        self.sca = SCA.from_dict(self.__sca_yml__)

    def export_custom(self, tailoring: Tailoring, custom_path: str) -> None:
        custom = deepcopy(self.__sca_yml__)
        policy = custom['policy']
        policy['name'] = tailoring.name
        policy['id'] = tailoring.id
        policy['description'] = tailoring.description
        policy['file'] = os.path.basename(custom_path)
        custom['checks'][:] = [
            check for check in custom['checks']
            if check.get('id') not in tailoring.decisions
        ]
        with open(custom_path, mode='w', encoding=ENCODING) as stream:
            self.__yaml__.dump(custom, stream)

    def export_exceptions(self, tailoring: Tailoring,
                          yml_path: str, md_path: str) -> None:
        sca = self.sca
        with open(self.baseline_path, 'rb') as baseline:
            digest = hashlib.sha256(baseline.read()).hexdigest()

        record = {
            'baseline': {
                'name': sca.policy.name,
                'id': sca.policy.id,
                'file': sca.policy.file,
                'sha256': digest,
            },
            'tailored_policy': {
                'name': tailoring.name,
                'id': tailoring.id,
                'file': f'{tailoring.id}.yml',
            },
            'generated_by': {'tool': 'wazuhscatune', 'version': VERSION},
            'generated_at': datetime.now(timezone.utc).isoformat(),
            'exceptions': [
                {
                    'check_id': check_id,
                    'title': decision.exception_check.title,
                    'justification': decision.justification,
                }
                for check_id, decision in tailoring.decisions.items()
            ],
        }

        with open(yml_path, mode='w', encoding=ENCODING) as stream:
            self.__yaml__.dump(record, stream)

        with open(md_path, mode='w', encoding=ENCODING) as stream:
            stream.write(f"# {escape_markdown_cell(tailoring.name)} Exception Record\n\n")
            stream.write(
                f"## {escape_markdown_cell(tailoring.name)} "
                f"({escape_markdown_cell(tailoring.id)})\n\n"
            )
            stream.write(f"{tailoring.description}\n\n")
            stream.write(
                f"Baseline: {escape_markdown_cell(sca.policy.name)} "
                f"(`{escape_markdown_cell(sca.policy.id)}`)  \n"
                f"SHA-256: `{digest}`\n\n"
            )
            stream.write("## Exceptions\n\n")
            stream.write("| Check ID | Check Name | Justification |\n")
            stream.write("| --- | --- | --- |\n")
            for check_id, decision in tailoring.decisions.items():
                stream.write(
                    f"| {check_id} | {escape_markdown_cell(decision.exception_check.title)} | "
                    f"{escape_markdown_cell(decision.justification)} |\n"
                )
            stream.write(
                "\n## Notes\n\nGenerated by `wazuhscatune`. "
                "Update the exception record and tailored policy together.\n"
            )
